### PR TITLE
Bump to Gluon v2019.1.x

### PR DESCRIPTION
**Pull request by grische**
- Bump to Gluon v2019.1.4
- Explicitly set mesh routing_algo to BATMAN_IV (no change compared v2018)
- Update custom Gluon 2018 workaround patches
- Add GLUON_DEPRECATED to only build sysupgrade images
- Drop tunneldigger-watchdog as it is implemented in Gluon directly https://github.com/freifunkMUC/packages-ffms/commit/15fecef53f7af0d17791c38898823d659c180cc8

### CODE REVIEW

**Comment by grische** [comment]
Confirmed working on WR841N v10.

**Comment by grische** [comment]
Depends on https://github.com/freifunkMUC/packages-ffms/pull/2 . Does anyone know how to properly test it?

**Review by GoliathLabs — APPROVED** [review]

**Comment by GoliathLabs** [comment]
> Depends on [freifunkMUC/packages-ffms#2](https://github.com/freifunkMUC/packages-ffms/pull/2) . Does anyone know how to properly test it?

`/usr/sbin/autoupdater-wifi-fallback -f`

**Comment by GoliathLabs** [comment]
Just to make sure, we aren't yet building the firmware with the patch for https://github.com/freifunk-gluon/gluon/security/advisories/GHSA-xqhj-fmc7-f8mv, right?

As this would make it difficult to persuade all APs to update to the final firmware.

**Comment by grische** [comment]
> Just to make sure, we aren't yet building the firmware with the patch for [GHSA-xqhj-fmc7-f8mv](https://github.com/freifunk-gluon/gluon/security/advisories/GHSA-xqhj-fmc7-f8mv), right?

>
> As this would make it difficult to persuade all APs to update to the final firmware.

We are and this is intentional. We have proper signatures in place.

**Pull request merged**
